% Returns a list of plugins which should be
function plugins = get_static_plugins

plugins = [...
    struct('name','toNanometers.m'),...
    struct('name','pspectrum.m'),...
    struct('name','plot3D.m'),...
    struct('name','density_plot.m'),...
    struct('name','density_column.m'),...
    struct('name','averageDensity.m'),...
    struct('name','generic_command.m'),...
    ];
